apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "frp.k8s.codecrafts.cf/v1alpha1",
          "kind": "FRPConnector",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "frp-tunnel-ingress",
              "app.kubernetes.io/instance": "frpconnector-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "frpconnector",
              "app.kubernetes.io/part-of": "frp-tunnel-ingress"
            },
            "name": "frpconnector-sample"
          },
          "spec": null
        }
      ]
    capabilities: Basic Install
    createdAt: "2024-04-10T20:11:56Z"
    operators.operatorframework.io/builder: operator-sdk-v1.34.1
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: frp-tunnel-ingress.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: FRPConnector is the Schema for the frpconnectors API
      displayName: FRPConnector
      kind: FRPConnector
      name: frpconnectors.frp.k8s.codecrafts.cf
      version: v1alpha1
  description: Ingress operator for fast-reverse-proxy tunnel based Kubernetes Ingress
    controller.
  displayName: frp-tunnel-ingress-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - frp.k8s.codecrafts.cf
          resources:
          - frpconnectors
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - frp.k8s.codecrafts.cf
          resources:
          - frpconnectors/finalizers
          verbs:
          - update
        - apiGroups:
          - frp.k8s.codecrafts.cf
          resources:
          - frpconnectors/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: frp-tunnel-ingress-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: frp-tunnel-ingress
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: frp-tunnel-ingress
          control-plane: controller-manager
        name: frp-tunnel-ingress-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.15.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: controller:latest
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: frp-tunnel-ingress-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: frp-tunnel-ingress-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - tunnel
  - frp
  - ingress
  links:
  - name: Frp Tunnel Ingress
    url: https://frp-tunnel-ingress.domain
  maintainers:
  - email: swghosh@codecrafts.cf
    name: swghosh
  maturity: alpha
  minKubeVersion: 1.25.0
  provider:
    name: k8s.codecrafts.cf
    url: https://github.com/swghosh/frp-tunnel-lb
  version: 0.0.1
